const USER_EVENTS = {
	VO_ADDED:'VO_ADDED',
	VIDEO_FINISHED:'VIDEO_FINISHED',
	VO_PLAYBACK_PROGRESS:'VO_PLAYBACK_PROGRESS',
	MEDIASOURCE_STATE:'MEDIASOURCE_STATE',
	PLAYLIST:'PLAYLIST',
}


const ERROR_TYPES = {
  FATAL: 'FATAL',
  RECOVER: 'RECOVER',
  APPEND_FAILED: 'APPEND_FAILED',
  MEDIASOURCE: 'MEDIASOURCE',
  VIDEO_ID: 'VIDEO_ID',
  SIDX: 'SIDX',
  VIDEO_VO: 'VIDEO_VO',
  NO_PLAYLISTS: 'NO_PLAYLISTS',
  EXHAUSED_VIDEO_REFERENCES: 'EXHAUSED_VIDEO_REFERENCES',
}

const MEDIASOURCE_TYPES = {
  VIDEO: 'video',
  AUDIO: 'audio',
}

const CONTROLLER_STATE = {
  IDLE: 'IDLE',
  BUSY: 'BUSY',
}

const MEDIASOURCE_STATE = {
  IDLE: 'IDLE',
  BUSY: 'BUSY',
}

const BEHAVIORS = {
  VIDEO_PASSED_DURATION: 'VIDEO_PASSED_DURATION'
}

export default {
  USER_EVENTS,
  ERROR_TYPES,
  MEDIASOURCE_TYPES,
  CONTROLLER_STATE,
  MEDIASOURCE_STATE,
  BEHAVIORS
}
