const ERROR_TYPES = {
  FATAL:'FATAL',
  RECOVER:'RECOVER',
  APPEND_FAILED:'APPEND_FAILED',
  MEDIASOURCE:'MEDIASOURCE',
  VIDEO_ID:'VIDEO_ID',
  SIDX:'SIDX',
  VIDEO_VO:'VIDEO_VO',
  NO_PLAYLISTS:'NO_PLAYLISTS',
  EXHAUSED_VIDEO_REFERENCES:'EXHAUSED_VIDEO_REFERENCES',
}

const MEDIASOURCE_TYPES = {
	VIDEO:'video',
	AUDIO:'audio',
}

const CONTROLLER_STATUS = {
	IDLE:'IDLE',
	BUSY:'BUSY',
}

export default {ERROR_TYPES, MEDIASOURCE_TYPES, CONTROLLER_STATUS}
